# Site
name: "Blogs of dantopia"
title: "dantopia blogs"
description: "Trang viết của dantopia.vn"
logo: 'assets/images/dantopia-logo-rounded.png'
favicon: 'assets/images/favicon.png'
baseurl: ""
google_analytics: 'UA-46278016-1'
disqus: ''
mailchimp-list: 'https://dantopia.us11.list-manage.com/subscribe/post?u=6045cdee0aa044c879cf5b18a&amp;id=c51661b0d3&amp;f_id=00ff98e0f0'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dantino:
    name: Tống V.T. Dân
    display_name: Tống V.T. Dân
    avatar: 'assets/images/dantino-avatar.jpeg'
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: dantpiavn@gmail.com
    web: https://dantopia.vn
    twitter: https://twitter.com/dantopiavn
    description: "Tống V.T. Dân là Cựu Đồng sáng lập và Giám đốc vận hành tại Gremsy J.S.C, Giám đốc và là nhà sáng lập Kodimo Co., Ltd, với kinh nghiệm hơn 16 năm về Kiến trúc phần mềm và các công nghệ hiện đại, bao gồm Phát triển phần cứng. Anh ấy cũng là người đam mê sáng chế và am hiểu các công cụ sáng chế, đổi mới sáng tạo. Anh ấy thích chia sẻ kiến ​​thức của mình vì lợi ích của người khác."
 

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
